### ISSUE TITLE
Kicad files

### ISSUE THREAD

**Issue by fifteenhex** [kanpapa/MC68EZ328#67]
Hi,

I would like to build one of these and see if I can get Linux 5.15 running on it.
Will you upload the kicad files soon?

Thanks,

Daniel

**Comment by kanpapa** [comment]
Hi, Daniel

Thank you for your interest in this project.
We are currently designing Rev.0.3, which allows network boards to be connected.

https://github.com/kanpapa/MC68EZ328/blob/main/Pictures/dragonone_rev03_2021-09-16_063345.png

We are planning to release the KiCad file when this design is completed.
Please wait a little longer.

You can also refer to my blog.
https://kanpapa.com/today/electronics/microcomputer/mc68ez328/

Regards,

Kazu

**Comment by kanpapa** [comment]
I pushed the KiCad file to the kanpapa-patch-1 branch.
The PCB is now being manufactured using this data.
I will merge it into main once I have confirmed that it works with this PCB.

**Comment by fifteenhex** [comment]
> I pushed the KiCad file to the kanpapa-patch-1 branch.
> The PCB is now being manufactured using this data.
> I will merge it into main once I have confirmed that it works with this PCB.

Awesome. Thank you!

**Comment by kanpapa** [comment]
#76 The board was fabricated using this KiCad data and it worked.
